export { default as boardsRouter } from './boards'
export { default as colorRouter } from './colors'
export { default as pixelsRouter } from './pixels'
export { default as pingRouter } from './ping'
export { default as authRouter } from './auth'
